[".config/ibus/rime/zh-hans-t-essay-bgw.gram"]
    type = "file"
    url = "http://assets.zzzsy.top/zh-hans-t-essay-bgw.gram"

[".config/ibus/rime/dicts/cn_dicts/8105.dict.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/8105.dict.yaml"
[".config/ibus/rime/dicts/cn_dicts/base.dict.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/base.dict.yaml"
[".config/ibus/rime/dicts/cn_dicts/ext.dict.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/ext.dict.yaml"
[".config/ibus/rime/dicts/cn_dicts/others.dict.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/others.dict.yaml"
[".config/ibus/rime/dicts/cn_dicts/sogou.dict.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/sogou.dict.yaml"
[".config/ibus/rime/dicts/cn_dicts/tencent.dict.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/tencent.dict.yaml"
