# Accessibility --------------------------------------

## Invert
##-#[ A plugin to invert the colors of the whole output.
[invert] #c'est default
toggle = <super> KEY_I
## Zoom
##-#[ A plugin to zoom in the desktop with the mouse.
[zoom] #c'est default
modifier = <super>


# Desktop ------------------------------------------------

## Alpha
##-#[ A plugin to change the opacity of windows.
[alpha]
modifer = <alt> <super>
## Expo
##-#[ A plugin to show an overview of all workspaces.
[expo]
background = \#241F31FF
select_workspace_1 = KEY_1
select_workspace_2 = KEY_2
select_workspace_3 = KEY_3
select_workspace_4 = KEY_4
select_workspace_5 = KEY_5
select_workspace_6 = KEY_6
select_workspace_7 = KEY_7
select_workspace_8 = KEY_8
select_workspace_9 = KEY_9
toggle = <super>
## Idle
##-#[ A plugin for idle settings, such as the screensaver and DPMS.

## Scale
##-#[ A plugin which shows all the windows on the current or on all workspaces, similar to GNOME's Overview.
[scale]
toggle = <super> KEY_P
duration = 300
## Viewport switcher
##-#[ A plugin to switch workspaces in a grid.
[vswitch]
binding_0 = <super> KEY_0
binding_1 = <super> KEY_1
binding_2 = <super> KEY_2
binding_3 = <super> KEY_3
binding_4 = <super> KEY_4
binding_5 = <super> KEY_5
binding_6 = <super> KEY_6
binding_7 = <super> KEY_7
binding_8 = <super> KEY_8
binding_9 = <super> KEY_9
with_win_0 = <super> <shift> KEY_0
with_win_1 = <super> <shift> KEY_1
with_win_2 = <super> <shift> KEY_2
with_win_3 = <super> <shift> KEY_3
with_win_4 = <super> <shift> KEY_4
with_win_5 = <super> <shift> KEY_5
with_win_6 = <super> <shift> KEY_6
with_win_7 = <super> <shift> KEY_7
with_win_8 = <super> <shift> KEY_8
with_win_9 = <super> <shift> KEY_9
## Viewport swipe
##-#[ A plugin to swipe workspaces in a grid.
[vswipe]
enable_smooth_transition = true

# Effect-----------------
## Animate
##-#[ A plugin which provides animations when a window is opened or closed.
[animate]
duration = 400
open_animation = zoom
## Blur
##-#[ A plugin to blur windows.
[blur]
blur_by_default = type is "toplevel"
kawase_degrade = 8
kawase_iterations = 2
kawase_offset = 2.000000
method = kawase
saturation = 1.000000
## Decoration
##-#[ Default decorations around XWayland windows.
[decoration]
ignore_views = all
## Wobby
##-#[ A plugin to get wobbly windows.
## Window rotate
##-#[ A plugin to rotate windows with the mouse. Move the mouse cursor to the center of the window to reset the rotation.
[wrot]
activate = <super> <ctrl> BTN_RIGHT


# General --------------------------------
## Autostart
##-#[ A plugin to run shell commands on startup.
[autostart]
autostart_wf_shell = false
bar = waybar
background = swaybg -i ~/Pictures/wallpaper/1.jpg -m fill
idle = swayidle befor-sleep swaylock
inputmethod = fcitx5
notification = dunst
outputs = kanshi
0_0 = systemctl --user import-environment
xdg = sleep 1 && (XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=sway /usr/lib/xdg-desktop-portal --replace & /usr/lib/xdg-desktop-portal-wlr)
0_environment = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY
xwayland = xrdb ~/.Xresources
authen = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
nutstore = sh -c "(sleep 30 && exec /opt/nutstore/bin/nutstore-pydaemon.py)"

## Command
##-#[ A plugin to bind key combo (key, button, touch) to execute shell commands.
[command]
binding_terminal = <super> KEY_ENTER
command_terminal = kitty

binding_launcher = <super> <shift> KEY_ENTER
command_launcher = rofi -show drun -no-default-config -config ~/.config/rofi/compact.rasi

binding_lock = <super> KEY_L
command_lock = exec bash ~/.config/sway/scripts/lock.sh

binding_logout = <super> <shift> KEY_E
command_logout = wlogout -r 50 -c 40

binding_screenshot = KEY_PRINT
command_screenshot = grim $(date '+%F_%T').png
binding_screenshot_interactive = <shift> KEY_PRINT
command_screenshot_interactive = slurp | grim -g - $(date '+%F_%T').png
binding_screenshot_snip = <ctrl> <alt> KEY_A
command_screenshot_snip = grim -g "$(slurp)" - | wl-copy

repeatable_binding_light_up = KEY_BRIGHTNESSUP
command_light_up = light -A 2 && light -O && notify-send "Brightness up"
repeatable_binding_light_down = KEY_BRIGHTNESSDOWN
command_light_down = light -U 2 && light -O && notify-send "Brightness down"

repeatable_binding_volume_up = KEY_VOLUMEUP
command_volume_up = pactl set-sink-volume @DEFAULT_SINK@ +3% && notify-send "Volume up"
repeatable_binding_volume_down = KEY_VOLUMEDOWN
command_volume_down = pactl set-sink-volume @DEFAULT_SINK@ -3% && notify-send "Volume down"
binding_volume_mute = KEY_MUTE
command_volume_mute = pactl set-sink-mute @DEFAULT_SINK@ toggle && notify-send "Volume mute"
binding_volume_micmute = KEY_MICMUTE
command_volume_micmute = pactl set-source-mute @DEFAULT_SOURCE@ toggle && notify-send "Mic mute"

binding_wechat = <super> KEY_O 
command_wechat = /opt/deepinwine/tools/sendkeys.sh w wechat 4
## Core
[core]
plugins = vswipe scale alpha animate autostart command decoration expo fast-switcher grid idle invert move oswitch place resize switcher vswitch windows-rules wm-actions wobbly wrot zoom firedecor
close_top_view = <super> KEY_Q | <alt> KEY_F4
vwidth = 3
vheight = 3
preferred_decoration_mode = client
xwayland = true
## Input
[input]
## Keyboard configuration
xkb_layout = us, fr
xkb_options = grp:win_space_toggle
## touchpad
mouse_accel_profile = adaptive
touchpad_accel_profile = adaptive
natural_scroll = true
touchpad_drag_lock = true
## OUtput
[output:eDP-1]
mode = 2560x1600@60.000000
layout = 0,0
transform = normal
scale = 2.000000
# Window management---------------------------
## Fast switcher
[fast-switcher]
activate = <alt> KEY_
[wm-actions]
toggle_fullscreen = <super> KEY_F
toggle_always_on_top = <super> KEY_T
[move]
activate = <super> BTN_LEFT
[resize]
activate = <super> BTN_RIGHT

[firedecor]
font = sans-serif
font_size = 21
active_font = \#1d1f21ff
inactive_font = \#1d1f21ff

border_size = 35 10
active_border = \#1d1f21e6
inactive_border = \#1d1f21e6
corner_radius = 15

outline_size = 0
active_outline = \#000000ff
inactive_outline = \#000000ff

button_size = 18
button_style = simple
normal_min = \#c89e2bff
hovered_min = \#fac636ff
normal_max = \#2ebb3aff
hovered_max = \#39ea49ff
normal_close = \#c24045ff
hovered_close = \#f25056ff
inactive_buttons = false

icon_size = 20
icon_theme = hicolor

active_accent = \#f5f5f5ff
inactive_accent = \#e1dfe1ff

layout = a | icon P4 title | minimize p maximize p close p Atrtl -
padding_size = 8

ignore_views = none
debug_mode = false
