# for_window
for_window [app_id="blueman-manager"] floating enable
for_window [app_id="wdisplays"] floating enable
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="kitty"] floating enable
