# Use pactl to adjust volume in PulseAudio.
bindsym XF86AudioRaiseVolume exec --no-startup-id "pactl set-sink-volume @DEFAULT_SINK@ +3%; notify-send 'Volume up'"
bindsym XF86AudioLowerVolume exec --no-startup-id "pactl set-sink-volume @DEFAULT_SINK@ -3%; notify-send 'Volume down'"
bindsym XF86AudioMute exec --no-startup-id "pactl set-sink-mute @DEFAULT_SINK@ toggle; notify-send 'Volume mute'"
bindsym XF86AudioMicMute exec --no-startup-id "pactl set-source-mute @DEFAULT_SOURCE@ toggle; notify-send 'Mic mute'"

# light-git
bindsym XF86MonBrightnessUp exec --no-startup-id "light -A 2; light -O; notify-send 'Brightness up'"
bindsym XF86MonBrightnessDown exec --no-startup-id "light -U 2; light -O; notify-send 'Brightness down'"
